/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Empleado;
import BackEnd.EmpleadoDAO;
import BackEnd.Sucursal;
import BackEnd.SucursalDAO;
import BackEnd.Utilidades;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author
 */
public class VistaEmpleadosActualizar extends javax.swing.JFrame {

    //Atributos
    private int idEmpleado;
    private int idSucursal;

    public int getIdEmpleado() {
        return idEmpleado;
    }

    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }

    public int getIdSucursal() {
        return idSucursal;
    }

    public void setIdSucursal(int idSucursal) {
        this.idSucursal = idSucursal;
    }
    
    
    
    
    /**
     * Creates new form SucursalesVistaAdmin
     */
    
    public VistaEmpleadosActualizar(){
        initComponents();
        Utilidades.cargarLogo(this, "logoLAYIWARE.png");
    }
    
    public VistaEmpleadosActualizar(int idEmpleado) {
        initComponents();
        
        this.idEmpleado = idEmpleado;
        
        Utilidades.cargarLogo(this, "logoLAYIWARE.png");
        
        SucursalDAO sucursalDAO = new SucursalDAO();
        List<Sucursal> sucursales = sucursalDAO.obtenerSucursales();
        System.out.println(sucursales);
        
        for(Sucursal sucursal : sucursales){
            cmbIdSucursal.addItem(String.valueOf(sucursal.getIdSucursal()));
        }
        
        EmpleadoDAO empleadoDAO = new EmpleadoDAO();
        Empleado empleado = empleadoDAO.obtenerEmpleado(idEmpleado);
        
        this.idSucursal = empleado.getIdSucursal();
        
        cmbIdSucursal.setSelectedItem(this.getIdSucursal());
        txtfNombre.setText(empleado.getNombre());
        txtfApellidoPaterno.setText(empleado.getApellidoPaterno());
        txtfApellidoMaterno.setText(empleado.getApellidoMaterno());
        txtfEmail.setText(empleado.getEmail());
        txtpPassword.setText(empleado.getContrasena());
        txtfSalario.setText(String.valueOf(empleado.getSalario()));
        txtfTelefono.setText(empleado.getTelefono());
        
        Sucursal sucursal = sucursalDAO.obtenerSucursalPorId(empleado.getIdSucursal());
        txtfNombreSucursal.setText(sucursal.getNombreSucursal());
        
        cmbIdSucursal.addItemListener(new ItemListener() {
                @Override
                public void itemStateChanged(ItemEvent e) {
                    if (e.getStateChange() == ItemEvent.SELECTED) {

                        String id = (String) cmbIdSucursal.getSelectedItem();
                        System.out.println(id);
                        Sucursal sucursal = sucursalDAO.obtenerSucursalPorId(Integer.valueOf(id));
                        txtfNombreSucursal.setText(sucursal.getNombreSucursal());
                        
                    }
                }
            });
        
        Utilidades.limitarCaracteres(txtfNombre, 20, "letras");
        Utilidades.limitarCaracteres(txtfApellidoPaterno, 20, "letras");
        Utilidades.limitarCaracteres(txtfApellidoMaterno, 20, "letras");
        Utilidades.limitarCaracteres(txtfSalario, 10, "numeros");
        Utilidades.limitarCaracteres(txtfTelefono, 10, "numeros");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblidSucursal = new javax.swing.JLabel();
        txtfTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtfNombreSucursal = new javax.swing.JTextField();
        txtfNombre = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        txtfSalario = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblSalario = new javax.swing.JLabel();
        lblApellidoPaterno = new javax.swing.JLabel();
        lblApellidoMaterno = new javax.swing.JLabel();
        txtfApellidoMaterno = new javax.swing.JTextField();
        txtfApellidoPaterno = new javax.swing.JTextField();
        txtfEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtpPassword = new javax.swing.JPasswordField();
        cmbIdSucursal = new javax.swing.JComboBox<>();
        btnActualizarEmpleados = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vista Empleados Actualizar");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        lblidSucursal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblidSucursal.setText("Id Sucursal");
        lblidSucursal.setPreferredSize(new java.awt.Dimension(300, 100));
        getContentPane().add(lblidSucursal);
        lblidSucursal.setBounds(190, 140, 140, 60);

        txtfTelefono.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfTelefono.setPreferredSize(new java.awt.Dimension(300, 100));
        txtfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtfTelefono);
        txtfTelefono.setBounds(700, 480, 410, 40);

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTelefono.setText("Teléfono");
        lblTelefono.setPreferredSize(new java.awt.Dimension(300, 100));
        getContentPane().add(lblTelefono);
        lblTelefono.setBounds(700, 440, 190, 40);

        txtfNombreSucursal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfNombreSucursal.setPreferredSize(new java.awt.Dimension(300, 100));
        txtfNombreSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNombreSucursalActionPerformed(evt);
            }
        });
        getContentPane().add(txtfNombreSucursal);
        txtfNombreSucursal.setBounds(320, 190, 280, 40);

        txtfNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfNombre.setPreferredSize(new java.awt.Dimension(300, 100));
        txtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtfNombre);
        txtfNombre.setBounds(700, 190, 410, 40);

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(1160, 30, 90, 90);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitulo.setText("Empleados");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(940, 80, 330, 48);

        txtfSalario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfSalario.setPreferredSize(new java.awt.Dimension(300, 100));
        txtfSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfSalarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtfSalario);
        txtfSalario.setBounds(190, 480, 410, 40);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setText("Nombre");
        lblNombre.setPreferredSize(new java.awt.Dimension(300, 100));
        getContentPane().add(lblNombre);
        lblNombre.setBounds(700, 150, 130, 40);

        lblSalario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSalario.setText("Salario");
        lblSalario.setPreferredSize(new java.awt.Dimension(300, 100));
        getContentPane().add(lblSalario);
        lblSalario.setBounds(190, 440, 190, 40);

        lblApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblApellidoPaterno.setText("Apellido Paterno");
        lblApellidoPaterno.setPreferredSize(new java.awt.Dimension(300, 100));
        getContentPane().add(lblApellidoPaterno);
        lblApellidoPaterno.setBounds(190, 250, 190, 40);

        lblApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblApellidoMaterno.setText("Apellido Materno");
        lblApellidoMaterno.setPreferredSize(new java.awt.Dimension(300, 100));
        getContentPane().add(lblApellidoMaterno);
        lblApellidoMaterno.setBounds(700, 250, 190, 40);

        txtfApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfApellidoMaterno.setPreferredSize(new java.awt.Dimension(300, 100));
        getContentPane().add(txtfApellidoMaterno);
        txtfApellidoMaterno.setBounds(700, 290, 410, 40);

        txtfApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfApellidoPaterno.setPreferredSize(new java.awt.Dimension(300, 100));
        txtfApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfApellidoPaternoActionPerformed(evt);
            }
        });
        getContentPane().add(txtfApellidoPaterno);
        txtfApellidoPaterno.setBounds(190, 290, 410, 40);

        txtfEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfEmail.setPreferredSize(new java.awt.Dimension(300, 100));
        txtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtfEmail);
        txtfEmail.setBounds(190, 380, 410, 40);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEmail.setText("Email");
        lblEmail.setPreferredSize(new java.awt.Dimension(300, 100));
        getContentPane().add(lblEmail);
        lblEmail.setBounds(190, 340, 190, 40);

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPassword.setText("Contraseña");
        lblPassword.setPreferredSize(new java.awt.Dimension(300, 100));
        getContentPane().add(lblPassword);
        lblPassword.setBounds(700, 340, 190, 40);

        txtpPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtpPassword.setText("jPasswordField1");
        getContentPane().add(txtpPassword);
        txtpPassword.setBounds(700, 380, 410, 40);

        cmbIdSucursal.setEditable(true);
        cmbIdSucursal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(cmbIdSucursal);
        cmbIdSucursal.setBounds(190, 190, 110, 40);

        btnActualizarEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        btnActualizarEmpleados.setText("Actualizar Empleado");
        btnActualizarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarEmpleados);
        btnActualizarEmpleados.setBounds(450, 570, 400, 60);

        lblFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\fondo interfaces final (1).jpg")); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 1280, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNombreActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VistaEmpleados vistaEmpleados = new VistaEmpleados();
        vistaEmpleados.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtfSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfSalarioActionPerformed

    private void txtfApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfApellidoPaternoActionPerformed

    private void txtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfEmailActionPerformed

    private void txtfNombreSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNombreSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNombreSucursalActionPerformed

    private void txtfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTelefonoActionPerformed

    private void btnActualizarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEmpleadosActionPerformed
        int idSucursal;
        try {
            idSucursal= Integer.parseInt((String) cmbIdSucursal.getSelectedItem());
        } catch (Exception e) {
            idSucursal= this.getIdSucursal();
        }
        System.out.println(idSucursal);
        String nombre = txtfNombre.getText();
        System.out.println(nombre);
        String apellidoPaterno = txtfApellidoPaterno.getText();
        System.out.println(apellidoPaterno);
        String apellidoMaterno = txtfApellidoMaterno.getText();
        System.out.println(apellidoMaterno);
        String email = txtfEmail.getText();
        System.out.println(email);
        String password = String.valueOf(txtpPassword.getPassword());
        System.out.println(password);
        double salario = Double.valueOf(txtfSalario.getText());
        System.out.println(salario);
        String telefono = txtfTelefono.getText();
        System.out.println(telefono);

        int result = JOptionPane.showConfirmDialog(
            new JFrame(),
            "¿Estas seguro de actualizar este empleado?",
            "Aseguradora - confirmación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if(result == JOptionPane.YES_OPTION){
            System.out.println(1);
            Empleado empleado = new Empleado(idSucursal, nombre, apellidoPaterno, apellidoMaterno, email, password, salario, true, telefono);
            EmpleadoDAO empleadoDAO = new EmpleadoDAO();

            try {
                // Ejemplo de inserción de una nuevo empleado

                empleadoDAO.actualizarEmpleado(empleado, this.idEmpleado);
                System.out.println("El empleado fue actualizado exitosamente.");
                JOptionPane.showMessageDialog(null, "El empleado fue actualizado exitosamente.", "Aseguradora", JOptionPane.INFORMATION_MESSAGE);
                VistaEmpleados vistaEmpleados = new VistaEmpleados();
                vistaEmpleados.setVisible(true);
                dispose();

            } catch (Exception e) {
                e.printStackTrace();
                System.out.println("Ocurrió un error al intentar actualizar al empleado " + e.getMessage());
                JOptionPane.showMessageDialog(null, "Ocurrió un error al intentar actualizar al empleado ", "Aseguradora", JOptionPane.ERROR_MESSAGE);
            }

        }else if (result == JOptionPane.NO_OPTION){
            System.out.println(2);

        }else {
            System.out.println(3);
        }

    }//GEN-LAST:event_btnActualizarEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleadosActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleadosActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleadosActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleadosActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEmpleadosActualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarEmpleados;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbIdSucursal;
    private javax.swing.JLabel lblApellidoMaterno;
    private javax.swing.JLabel lblApellidoPaterno;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblidSucursal;
    private javax.swing.JTextField txtfApellidoMaterno;
    private javax.swing.JTextField txtfApellidoPaterno;
    private javax.swing.JTextField txtfEmail;
    private javax.swing.JTextField txtfNombre;
    private javax.swing.JTextField txtfNombreSucursal;
    private javax.swing.JTextField txtfSalario;
    private javax.swing.JTextField txtfTelefono;
    private javax.swing.JPasswordField txtpPassword;
    // End of variables declaration//GEN-END:variables
}
