/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Seguro;
import BackEnd.SeguroDAO;
import BackEnd.Sucursal;
import BackEnd.SucursalDAO;
import BackEnd.Utilidades;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class VistaSeguros extends javax.swing.JFrame {

    /**
     * Creates new form VistaLogin
     */
    public VistaSeguros() {
        initComponents();
        
        Utilidades.cargarLogo(this, "logoLAYIWARE.png");
        
        
            DefaultTableModel model = (DefaultTableModel) tblSeguros.getModel();
            
            SeguroDAO seguroDAO = new SeguroDAO();
            
            // Obtener todos los productos
            List<Seguro> seguros = seguroDAO.obtenerSeguros();
            System.out.println("Todas los seguros:");
            for (Seguro seguro : seguros) {
                
                model.addRow(new Object[]{
                    seguro.getIdSeguro(),
                    seguro.getIdAsegurado(),
                    seguro.getCantidadAsegurada(),
                    seguro.getFolio(),
                    seguro.getVigencia(),
                    seguro.getFechaRecepcion(),
                    seguro.getTelefono(),
                    seguro.getTipoSeguro()
                });
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeguros = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBorrar2 = new javax.swing.JButton();
        zlblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vista Seguros");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        tblSeguros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idSeguro", "idAsegurado", "Cantidad asegurada", "Folio", "Vigencia", "Fecha recepcion", "Telefono", "Tipo de seguro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSeguros);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 60, 1130, 610);

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(20, 300, 90, 90);

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ver.png"))); // NOI18N
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer);
        btnVer.setBounds(20, 180, 90, 90);

        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Crear.png"))); // NOI18N
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear);
        btnCrear.setBounds(20, 60, 90, 90);

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(20, 540, 90, 90);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Seguros");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1090, 0, 330, 48);

        btnBorrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Borrar.png"))); // NOI18N
        btnBorrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar2);
        btnBorrar2.setBounds(20, 420, 90, 90);

        zlblFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\fondo interfaces final (1).jpg")); // NOI18N
        getContentPane().add(zlblFondo);
        zlblFondo.setBounds(0, 0, 1273, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int selectedRow = tblSeguros.getSelectedRow();
        
        if(selectedRow != -1){
            int idSeguro = (int) tblSeguros.getValueAt(selectedRow, 0);
            int idAsegurado = (int) tblSeguros.getValueAt(selectedRow, 1);
            System.out.println(idSeguro);
            VistaSegurosActualizar vistaSegurosActualizar = new VistaSegurosActualizar(idSeguro, idAsegurado);
            vistaSegurosActualizar.setVisible(true);
            dispose();
            
        }else{
             JOptionPane.showMessageDialog(null, "Por favor selecciona un seguro");
        }
        
        
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        int selectedRow = tblSeguros.getSelectedRow();
        
        if(selectedRow != -1){
            int idSeguro = (int) tblSeguros.getValueAt(selectedRow, 0);
            int idAsegurado = (int) tblSeguros.getValueAt(selectedRow, 1);
            System.out.println(idSeguro);
            VistaSegurosVer vistaSegurosVer = new VistaSegurosVer(idSeguro, idAsegurado);
            vistaSegurosVer.setVisible(true);
            dispose();
        
        }else{
             JOptionPane.showMessageDialog(null, "Por favor selecciona un seguro");
        }
        
        
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        VistaSegurosCrear vistaSegurosCrear = new VistaSegurosCrear();
        vistaSegurosCrear.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VistaMenu vistaMenu = new VistaMenu();
        vistaMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBorrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar2ActionPerformed
        int selectedRow = tblSeguros.getSelectedRow();
        
        if(selectedRow != -1){
            int idSeguro = (int) tblSeguros.getValueAt(selectedRow, 0);
            System.out.println(idSeguro);
            
            int result = JOptionPane.showConfirmDialog(
                new JFrame(),
                "¿Estas seguro de querer borrar este seguro?", 
                "Aseguradora",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );

            if(result == JOptionPane.YES_OPTION){
                System.out.println(1);
                SeguroDAO seguroDAO = new SeguroDAO();
                int id = seguroDAO.eliminarSeguro(idSeguro);
                if(id != 0){
                    JOptionPane.showMessageDialog(null, "El seguro fue eliminado exitosamente.", "Aseguradora", JOptionPane.INFORMATION_MESSAGE);
                    VistaSeguros vistaSeguros = new VistaSeguros();
                    vistaSeguros.setVisible(true);
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "El seguro no se pudo eliminar.", "Aseguradora", JOptionPane.ERROR_MESSAGE);
                }
            }else if (result == JOptionPane.NO_OPTION){
                System.out.println(2);
            }else {
                System.out.println(3);
            } 
        }else{
             JOptionPane.showMessageDialog(null, "Por favor selecciona un seguro");
        }
        
    }//GEN-LAST:event_btnBorrar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSeguros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar2;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSeguros;
    private javax.swing.JLabel zlblFondo;
    // End of variables declaration//GEN-END:variables
}
